#!/bin/bash

#BSUB -J finalproject
#BSUB -q ser
#BSUB -n 16
#BSUB -e error
#BSUB -o output
#BSUB -R "span[ptile=40]"

module purge
module load intel/2018.4
module load mpi/intel/2018.4


#for implicit
# the fixed-size scalabiling
mpirun -np 1 ./implicit -n 10000 -dt 0.1 -log_view
mpirun -np 2 ./implicit -n 10000 -dt 0.1 -log_view
mpirun -np 4 ./implicit -n 10000 -dt 0.1 -log_view
mpirun -np 8 ./implicit -n 10000 -dt 0.1 -log_view
mpirun -np 16 ./implicit -n 10000 -dt 0.1 -log_view
#isogranular scaling
mpirun -np 1 ./implicit -n 1000 -dt 0.1 -log_view
mpirun -np 2 ./implicit -n 1414 -dt 0.1 -log_view
mpirun -np 3 ./implicit -n 1732 -dt 0.1 -log_view
mpirun -np 4 ./implicit -n 2000 -dt 0.1 -log_view
mpirun -np 5 ./implicit -n 2236 -dt 0.1 -log_view
mpirun -np 6 ./implicit -n 2449 -dt 0.1 -log_view
mpirun -np 7 ./implicit -n 2645 -dt 0.1 -log_view
mpirun -np 8 ./implicit -n 2828 -dt 0.1 -log_view
mpirun -np 9 ./implicit -n 3000 -dt 0.1 -log_view
mpirun -np 10 ./implicit -n 3162 -dt 0.1 -log_view


#convergence behavior
#for gmres
mpirun -np 1 ./implicit -n 1000 -dt 0.1 -log_view -ksp_monitor -ksp_type gmres -pc_type jacobi
mpirun -np 1 ./implicit -n 1000 -dt 0.1 -log_view -ksp_monitor -ksp_type gmres -pc_type asm
#(d)
mpirun -np 1 ./implicit -n 1000 -dt 0.1 -log_view -ksp_monitor -ksp_type preonly -pc_type lu -pc_factor_mat_solver mumps
